cloud:
  aws:
    credentials:
      access-key: CLAVEDEACCESOEJEMPLO
      secret-key: CLAVESECRETADEEJEMPLO
    region:
      static: region-de-ejemplo
    stack:
      auto: false

spring:
  datasource1:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aurora57.cluster-cfkwcska1oxw.us-east-1.rds.amazonaws.com:3306/casouso
    username: admin
    password: admin123
  datasource:
    url: jdbc:h2:mem:springbatch;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  batch:
    initialize-schema: NEVER
    job.enabled: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml
  jpa:
     show-sql: true
  cloud:
    stream:
      bindings:
        fileReader-out-0:
          destination: channel01


#---
application:
  file:
      name: nombreDelArchivo
  bucket:
    name: nombreDelBucket


