cloud:
  aws:
    credentials:
      access-key: ACCESSKEYEJEMPLO
      secret-key: SECRETKEYEJEMPLO
    region:
      static: REGIONEJEMPLO
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/casouso?autoReconnect=true&useSSL=false
    username: username
    password: password
  batch:
    jdbc:
      initialize-schema: NEVER
    job.enabled: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.xml
  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
       naming:
         implicity-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    stream:
      bindings:
        fileReader-out-0:
          destination: channel01


#---
application:
  file:
    name: ARCHIVOEJEMPLO
  bucket:
    name: BUCKETEJEMPLO

